Repository peauty/peauty-BE, pull requests merged in 2024-12, with the labels that each got.

#25 [Peauty-81] Create Domain & Entity about Review, Addy
  peauty-domain/src/main/java/com/peauty/domain/puppy/Puppy.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-domain/src/main/java/com/peauty/domain/review/ContentGeneral.java
  peauty-domain/src/main/java/com/peauty/domain/review/Review.java
  peauty-domain/src/main/java/com/peauty/domain/review/ReviewRating.java
  peauty-persistence/src/main/java/com/peauty/persistence/puppy/AddyEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/puppy/PuppyRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewImageEntity.java
Labels: enhancement

#28 [PEAUTY-80] ReDesign Designer Domain & develop Designer CRUD
  peauty-designer-api/src/main/java/com/peauty/designer/business/auth/AuthServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerService.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/UpdateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/workspace/WorkspacePort.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/workspace/WorkspaceAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/workspace/WorkspaceMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/DesignerController.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Badge.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Designer.java
  peauty-domain/src/main/java/com/peauty/domain/designer/DesignerInfo.java
  peauty-domain/src/main/java/com/peauty/domain/designer/License.java
  peauty-domain/src/main/java/com/peauty/domain/designer/PaymentOption.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Rating.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Scissor.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Shop.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Workspace.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/BadgeRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerBadgeEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerBadgeRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerInfoEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/LicenseEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/LicenseRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/RatingEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/RatingRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/ShopEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/WorkspaceEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/WorkspaceRepository.java
Labels: enhancement

#32 [PEAUTY-100] Create Get Puppy Profile API
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/PuppyPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/PuppyService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/PuppyServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/GetPuppyProfileResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/GetPuppyProfilesResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/customer/CustomerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/puppy/PuppyAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/PuppyController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/GetPuppyProfileResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/GetPuppyProfilesResponse.java
  peauty-persistence/src/main/java/com/peauty/persistence/puppy/PuppyRepository.java
Labels: enhancement

#34 [PEAUTY-117] workspace address 필드 추가 및 로직 수정
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/UpdateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerProfileResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerProfileRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerProfileResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerProfileResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/workspace/WorkspaceMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerProfileResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Designer.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Workspace.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerBadgeEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/RatingEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/WorkspaceEntity.java
Labels: enhancement

#37 [PEAUTY-95] Create Searching Around Workspace
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspacesResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspacePort.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/customer/CustomerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/customer/CustomerMapper.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/workspace/WorkspaceAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspaceResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspacesResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Workspace.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/WorkspaceRepository.java
Labels: enhancement

#40 [PEAUTY-98] Add Column 'License Verification' in License
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/customer/CustomerMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/UpdateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/workspace/WorkspaceMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Designer.java
  peauty-domain/src/main/java/com/peauty/domain/designer/License.java
  peauty-domain/src/main/java/com/peauty/domain/designer/LicenseVerification.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Rating.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Scissor.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Scissors.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-domain/src/main/java/com/peauty/domain/review/ContentGeneral.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/LicenseEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/RatingEntity.java
Labels: enhancement

#42 [PEAUTY-119] designer response estimate, complete gromming
  peauty-customer-api/src/main/java/com/peauty/customer/business/bidding/CustomerBiddingServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/bidding/CustomerBiddingController.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/BiddingProcessPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/BiddingThreadPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/DesignerBiddingPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/DesignerBiddingServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/EstimateProposalPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/dto/CompleteGroomingCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/dto/SendEstimateCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/bidding/dto/SendEstimateResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/BiddingMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/BiddingProcessAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/BiddingThreadAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/DesignerBiddingAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/DesignerBiddingMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/EstimateProposalAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/EstimateProposalMapper.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/bidding/DesignerBiddingController.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/bidding/dto/CompleteGroomingResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/bidding/dto/SendEstimateRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/bidding/dto/SendEstimateResponse.java
  peauty-domain/src/main/java/com/peauty/domain/bidding/Estimate.java
  peauty-persistence/src/main/java/com/peauty/persistence/bidding/estimate/DesignerBiddingRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/bidding/estimate/EstimateEntity.java
Labels: enhancement

#47 [PEAUTY-114] 고객 프로필 조회 전화번호 필드 추가
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetCustomerProfileResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetCustomerProfileResponse.java
Labels: bug

#45 [PEAUTY-95] Adding Rating, Badges about GetAroundWorkspace API
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/designer/DesignerPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspacePort.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/customer/CustomerMapper.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/workspace/WorkspaceAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspaceResponse.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/BadgeRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerBadgeRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/RatingEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/RatingRepository.java
Labels: documentation, enhancement

#48 [PEAUTY-142] Get Designer's Badges by Designer
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerService.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerBadgesResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/DesignerController.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerBadgesResponse.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/DesignerBadgeRepository.java
Labels: enhancement

#50 [PEAUTY-149] Get Designer's Badge By Customer
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetDesignerBadgesForCustomerResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/designer/DesignerPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/designer/DesignerService.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetDesignerBadgesForCustomerResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/DesignerController.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceResponse.java
Labels: enhancement

#51 [PEAUTY-150] Add Column 'color' in Badge
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetDesignerBadgesForCustomerResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerBadgesResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Badge.java
  peauty-domain/src/main/java/com/peauty/domain/designer/BadgeColor.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/BadgeEntity.java
Labels: enhancement

#53 [PEAUTY-143] update Designer's Badges Option
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerService.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateRepresentativeBadgeCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateRepresentativeBadgeResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/DesignerController.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateRepresentativeBadgeRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateRepresentativeBadgeResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Badge.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/badge/DesignerBadgeRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/mapper/BadgeMapper.java
Labels: enhancement

#56 [PEAUTY-154] Refactoring Review Domain
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/RegisterReviewCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/RegisterReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/RegisterReviewResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/RegisterReviewResponse.java
  peauty-domain/src/main/java/com/peauty/domain/review/Review.java
  peauty-domain/src/main/java/com/peauty/domain/review/ReviewImage.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewRepository.java
Labels: enhancement

#57 [PEAUTY-158] Response & Request Change English to Korean
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/GetPuppyDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/GetPuppyProfileResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/RegisterPuppyResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/RegisterPuppyRequest.java
Labels: enhancement

#55 [PEAUTY-135] payment order logic first development
  peauty-customer-api/build.gradle
  peauty-customer-api/src/main/java/com/peauty/customer/PeautyCustomerApplication.java
  peauty-designer-api/build.gradle
  peauty-domain/src/main/java/com/peauty/domain/payment/Order.java
  peauty-payment/build.gradle
  peauty-payment/src/main/java/com/peauty/payment/PaymentConfig.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentPort.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentService.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentServiceImpl.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CompletePaymentCommand.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CompletePaymentResult.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/OrderCommand.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/OrderResult.java
  peauty-payment/src/main/java/com/peauty/payment/implementation/PaymentAdapter.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/PaymentController.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/PeautyPaymentResponseAdvice.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CompletePaymentRequest.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CompletePaymentResponse.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/OrderRequest.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/OrderResponse.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/OrderEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/OrderRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/PaymentMapper.java
Labels: enhancement

#59 [PEAUTY-156] create designerProfile method in designerAdapter
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/designer/DesignerPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspacePort.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/workspace/WorkspaceAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/workspace/WorkspaceAdapter.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Badge.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Designer.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/mapper/DesignerMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/rating/RatingRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/workspace/WorkspaceRepository.java
Labels: enhancement

#60 [PEAUTY-167] AroundWorkspace Color field / Register Review
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/RegisterReviewCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/RegisterReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/RegisterReviewResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/RegisterReviewCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/RegisterReviewResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspaceResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/RegisterReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/RegisterReviewResponse.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewImageRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewMapper.java
Labels: enhancement

#62 [PEAUTY-172] Impl Update/Delete Review API
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetEstimateDataResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetEstimateDataResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/UpdateReviewCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/UpdateReviewResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/ReviewController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/DeleteReviewResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/RegisterReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/RegisterReviewResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/UpdateReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/UpdateReviewResponse.java
  peauty-domain/src/main/java/com/peauty/domain/bidding/EstimateProposal.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-domain/src/main/java/com/peauty/domain/review/Review.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewImageRepository.java
Labels: enhancement

#64 [PEAUTY-180] Add Enum Badge Type
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspaceResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetDesignerBadgesForCustomerResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Badge.java
  peauty-domain/src/main/java/com/peauty/domain/designer/BadgeColor.java
  peauty-domain/src/main/java/com/peauty/domain/designer/BadgeType.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/badge/BadgeEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/mapper/BadgeMapper.java
Labels: enhancement

#65 [PEAUTY-186] Load DesignerId, Change puppySize
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/GetPuppyDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/RegisterPuppyResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspaceResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/RegisterPuppyRequest.java
Labels: enhancement

#66 [PEAUTY-186] Load DesignerId, Change puppySize, Disease Confirmed
  peauty-domain/src/main/java/com/peauty/domain/puppy/Disease.java
Labels: enhancement

#68 [PEAUTY-187] health check - actuator build gradle 추가
  peauty-customer-api/build.gradle
  peauty-designer-api/build.gradle
Labels: enhancement

#76 [PEAUTY-198] Convert ResponseBody Eng -> Kor
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/RegisterPuppyRequest.java
Labels: enhancement

#74 [PEAUTY-196] Convert BirthDate to Age
  peauty-customer-api/src/main/java/com/peauty/customer/business/designer/DesignerPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/PuppyServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/GetPuppyDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/GetPuppyProfileResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/RegisterPuppyCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/RegisterPuppyResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/puppy/dto/UpdatePuppyDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspacePort.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/workspace/WorkspaceAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/GetPuppyDetailResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/GetPuppyProfileResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/RegisterPuppyRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/RegisterPuppyResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Workspace.java
  peauty-domain/src/main/java/com/peauty/domain/puppy/Puppy.java
  peauty-domain/src/main/java/com/peauty/domain/puppy/PuppyAgeInfo.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-domain/src/test/java/puppy/PuppyAgeInfoScenarioTest.java
  peauty-persistence/src/main/java/com/peauty/persistence/puppy/PuppyMapper.java
Labels: enhancement

#71 [PEAUTY-170] Impl Review Rating & Review Count Logic
  peauty-domain/src/test/java/review/ReviewCountingTest.java
Labels: enhancement

#73 [PEAUTY-169] Payment prototype develope
  peauty-customer-api/build.gradle
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/config/PaymentConfig.java
  peauty-customer-api/src/main/resources/application.yml
  peauty-designer-api/build.gradle
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/bidding/BiddingProcessAdapter.java
  peauty-designer-api/src/main/resources/application.yml
  peauty-domain/src/main/java/com/peauty/domain/payment/Order.java
  peauty-domain/src/main/java/com/peauty/domain/payment/OrderStatus.java
  peauty-domain/src/main/java/com/peauty/domain/payment/Payment.java
  peauty-domain/src/main/java/com/peauty/domain/payment/PaymentStatus.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-payment/build.gradle
  peauty-payment/src/main/java/com/peauty/payment/PaymentConfig.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentPort.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentService.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentServiceImpl.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CompletePaymentCallbackCommand.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CompletePaymentCallbackResult.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CompletePaymentCommand.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CompletePaymentResult.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CreateOrderCommand.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CreateOrderResult.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/OrderCommand.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/OrderResult.java
  peauty-payment/src/main/java/com/peauty/payment/implementation/PaymentAdapter.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/PaymentController.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CompletePaymentCallbackRequest.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CompletePaymentCallbackResponse.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CompletePaymentRequest.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CompletePaymentResponse.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CreateOrderRequest.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CreateOrderResponse.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/OrderRequest.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/OrderResponse.java
  peauty-payment/src/main/resources/application.yml
  peauty-persistence/src/main/java/com/peauty/persistence/payment/OrderEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/PaymentEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/PaymentMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/PaymentRepository.java
Labels: enhancement

#79 [PEAUTY-199] Workspace Change enum type value (Request(english), Response(korean))
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/DesignerController.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceResponse.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/workspace/WorkspaceEntity.java
  peauty-persistence/src/main/resources/application-persistence.yml
Labels: :lady_beetle: 버그, :hammer_and_wrench: 기능

#81 [PEAUTY-220] Convert desiredDateTime from LocalDateTime to String
  peauty-customer-api/src/main/java/com/peauty/customer/business/bidding/dto/SendEstimateProposalCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/bidding/dto/SendEstimateProposalRequest.java
  peauty-domain/src/main/java/com/peauty/domain/bidding/EstimateProposal.java
  peauty-persistence/src/main/java/com/peauty/persistence/bidding/estimate/EstimateProposalEntity.java
Labels: :hammer_and_wrench: 기능

#83 [PEAUTY-222] Move Workspace Detail API from Designer Module to Customer Module
  peauty-auth/src/main/java/com/peauty/auth/config/SecurityConfig.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspaceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspaceService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetAroundWorkspacesResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetDesignerWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspaceResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetAroundWorkspacesResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/DesignerController.java
Labels: :hammer: 리팩토링

#85 [PEUATY-207] Impl Mockup Unit Test About Auth & Customer
  peauty-customer-api/build.gradle
  peauty-customer-api/src/test/java/auth/AuthServiceImplTest.java
  peauty-customer-api/src/test/java/customer/CustomerServiceImplTest.java
Labels: :hammer_and_wrench: 기능

#86 [PEAUTY-213] Impl image generator and dalle client
  peauty-addy/build.gradle
  peauty-addy/src/main/java/com/peauty/addy/AddyConfig.java
  peauty-addy/src/main/java/com/peauty/addy/FeignConfig.java
  peauty-addy/src/main/java/com/peauty/addy/dalle/DalleClient.java
  peauty-addy/src/main/java/com/peauty/addy/dalle/DalleEditImageResponse.java
  peauty-addy/src/main/java/com/peauty/addy/dalle/ImageMaskGenerator.java
  peauty-addy/src/main/resources/application.properties
  peauty-addy/src/main/resources/application.yml
Labels: :hammer_and_wrench: 기능

#90 [PEAUTY-246] Add Badge Type (General, Scissors) to Response Values
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetDesignerWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerBadgesResponse.java
  peauty-persistence/src/main/resources/properties/badge-init.sql
  peauty-persistence/src/main/resources/properties/designer-badge-init.sql
Labels: :hammer: 리팩토링

#80 [PEAUTY-210] Add Logic for Process and Thread State Changes on Payment Completion
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/puppy/dto/RegisterPuppyRequest.java
  peauty-domain/src/main/java/com/peauty/domain/payment/Order.java
  peauty-domain/src/main/java/com/peauty/domain/payment/OrderStatus.java
  peauty-domain/src/main/java/com/peauty/domain/payment/Payment.java
  peauty-domain/src/main/java/com/peauty/domain/payment/PaymentStatus.java
  peauty-payment/build.gradle
  peauty-payment/src/main/java/com/peauty/payment/business/BiddingProcessPort.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentService.java
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentServiceImpl.java
  peauty-payment/src/main/java/com/peauty/payment/business/PuppyPort.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CreateOrderCommand.java
  peauty-payment/src/main/java/com/peauty/payment/implementation/BiddingProcessAdapter.java
  peauty-payment/src/main/java/com/peauty/payment/implementation/PuppyAdapter.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/PaymentController.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CompletePaymentCallbackRequest.java
  peauty-payment/src/main/java/com/peauty/payment/presentation/dto/CreateOrderRequest.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/OrderEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/PaymentEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/payment/PaymentMapper.java
Labels: :hammer_and_wrench: 기능

#97 [PEAUTY-temp3] Refactor BannerImageUrl to Support List Structure and Update Related Implementations
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetEstimateDataResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetEstimateDataResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspaceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspacePort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetDesignerWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/workspace/WorkspaceAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/workspace/WorkspaceAdapter.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/CreateDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/GetDesignerWorkspaceResponse.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceRequest.java
  peauty-designer-api/src/main/java/com/peauty/designer/presentation/controller/designer/dto/UpdateDesignerWorkspaceResponse.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Workspace.java
  peauty-payment/src/main/java/com/peauty/payment/implementation/PaymentAdapter.java
  peauty-persistence/src/main/java/com/peauty/persistence/customer/CustomerMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/mapper/WorkspaceMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/workspace/BannerImageEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/workspace/BannerImageRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/workspace/WorkspaceEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/workspace/WorkspaceRepository.java
  peauty-persistence/src/main/resources/properties/banner-image-init.sql
  peauty-persistence/src/main/resources/properties/workspace-init.sql
Labels: :hammer: 리팩토링

#93 [PEAUTY-temp2] Impl Get Designer's Reviews
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetDesignerReviewsResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/ReviewController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetDesignerReviewsResponse.java
  peauty-domain/src/main/java/com/peauty/domain/customer/Customer.java
  peauty-domain/src/main/java/com/peauty/domain/review/Review.java
  peauty-persistence/src/main/java/com/peauty/persistence/bidding/estimate/EstimateProposalRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/customer/CustomerRepository.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewRepository.java
Labels: :hammer_and_wrench: 기능

#94 [PEAUTY-239] Addy: Development Environment Setup for Collaboration
  peauty-addy/src/main/java/com/peauty/addy/FeignConfig.java
  peauty-addy/src/main/java/com/peauty/addy/dalle/DalleClient.java
  peauty-addy/src/main/java/com/peauty/addy/dalle/DalleClientImpl.java
  peauty-addy/src/main/resources/application.yml
  peauty-customer-api/build.gradle
  peauty-customer-api/src/main/java/com/peauty/customer/PeautyCustomerApplication.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/addy/AddyPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/addy/AddyService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/addy/AddyServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/addy/dto/CreateAddyImageCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/addy/dto/CreateAddyImageResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/addy/dto/CreateMaskingResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/addy/AddyAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/addy/AddyController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/addy/dto/CreateAddyImageRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/addy/dto/CreateAddyImageResponse.java
  peauty-domain/src/main/java/com/peauty/domain/addy/AddyImage.java
  peauty-persistence/src/main/java/com/peauty/persistence/addy/AddyEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/addy/AddyMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/addy/AddyRepository.java
Labels: :hammer_and_wrench: 기능

#100 [PEAUTY-temp6] hotfix Update Review
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewMapper.java
Labels: :lady_beetle: 버그, :grey_question: 이슈!

#101 [PEAUTY-temp7] Enhance Workspace Update API to Handle All Scenarios
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/workspace/WorkspaceAdapter.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/workspace/BannerImageEntity.java
Labels: :lady_beetle: 버그, :grey_question: 이슈!

#104 [PEAUTY-temp10] Workspace YearsOfExperience Update API fix
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetAroundWorkspaceResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/dto/GetDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/CreateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/GetDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceResult.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerAdapter.java
  peauty-domain/src/main/java/com/peauty/domain/designer/Designer.java
  peauty-persistence/src/main/java/com/peauty/persistence/customer/CustomerMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/designer/mapper/DesignerMapper.java
Labels: :lady_beetle: 버그

#102 [PEAUTY-temp8] feat AllReviews & refactor contentGeneral Options
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetReviewDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetUserReviewsResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/RegisterReviewCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/RegisterReviewResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/UpdateReviewCommand.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/UpdateReviewResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/ReviewController.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetReviewDetailResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetUserReviewsResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/RegisterReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/RegisterReviewResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/UpdateReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/UpdateReviewResponse.java
  peauty-domain/src/main/java/com/peauty/domain/review/Review.java
  peauty-domain/src/test/java/review/ReviewCountingTest.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewEntity.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewMapper.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewRepository.java
Labels: :hammer_and_wrench: 기능

#105 [PEAUTY-temp13] Adding biddingProcessId info in Review
  peauty-customer-api/src/main/java/com/peauty/customer/business/bidding/BiddingProcessPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetReviewDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/bidding/BiddingProcessAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetReviewDetailResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetUserReviewsResponse.java
  peauty-persistence/src/main/java/com/peauty/persistence/bidding/process/BiddingProcessRepository.java
Labels: :hammer_and_wrench: 기능

#106 [PEAUTY-temp14] feat: Swagger Docs about Review
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetDesignerReviewsResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetReviewDetailResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetUserReviewsResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/RegisterReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/RegisterReviewResponse.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/UpdateReviewRequest.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/UpdateReviewResponse.java
Labels: :book: 문서

#107 [PEAUTY-248] Add field puppyId - GetUserReviews
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetReviewDetailResult.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/dto/GetReviewDetailResponse.java
Labels: :book: 문서

#111 [PEAUTY-258] Workspace Update API for License Saving
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerPort.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/DesignerServiceImpl.java
  peauty-designer-api/src/main/java/com/peauty/designer/business/designer/dto/UpdateDesignerWorkspaceCommand.java
  peauty-designer-api/src/main/java/com/peauty/designer/implementation/designer/DesignerAdapter.java
Labels: :lady_beetle: 버그

#112 [PEAUTY-259] refactor update,delete review PathVariable
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewPort.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewService.java
  peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
  peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/review/ReviewController.java
  peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewRepository.java
Labels: :hammer_and_wrench: 기능

#113 [PEAUTY-260] Fix Order API
  peauty-payment/src/main/java/com/peauty/payment/business/PaymentServiceImpl.java
  peauty-payment/src/main/java/com/peauty/payment/business/dto/CreateOrderCommand.java
Labels: :lady_beetle: 버그

#115 [PEAUTY-262] Add Enum ContentGeneral - Good Cost
  peauty-domain/src/main/java/com/peauty/domain/review/ContentGeneral.java
Labels: :hammer_and_wrench: 기능

#116 [PEUATY-263] refactor Logic removing reviewImages
  peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
  peauty-domain/src/main/java/com/peauty/domain/review/ContentGeneral.java
  peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewImageRepository.java
Labels: :lady_beetle: 버그
